stages:
  - test
# Set up cache, so we have to run composer update between builds, speeding it up!
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/
test:
  image: edbizarro/gitlab-ci-pipeline-php:7.4
  stage: test
  services:
    - mariadb:10.3.11
variables:
  MYSQL_DATABASE: "test"
  MYSQL_ROOT_PASSWORD: "secret"
script:
  - composer update --no-interaction --no-progress  --prefer-dist --optimize-autoloader --ignore-platform-reqs
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan config:cache
  - php artisan route:cache
  - npm install
  - npm run prod
  - php artisan migrate --seed
  - php artisan storage:link
  - php artisan serve &
  - vendor/bin/phpunit
